apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: exporter
  namespace: grafana-tst
spec:
  folder: "grafana"
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: grafana-tst
  json: >
